stages:
  - prepare
  - check_update
  - build
  - push

image: docker:latest

services:
  - name: docker:dind
    command: ["--tls=false"]

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375

before_script:
  - docker info
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REGISTRY" -u "$DOCKER_USERNAME" --password-stdin

include:
  - local: .ci/waf.yml
  - local: .ci/guacamole.yml

  
